import { ArrowUpRight, CircleCheck, ScanLine, Sparkles } from 'lucide-react';

export default function FindNarrative({ locale }: { locale: 'en' | 'es' }) {
  const copy = locale === 'es'
    ? { title: 'Un hallazgo se convierte en una mejor compra', body: 'La tecnología de APERFY no está para impresionar por sí sola. Está para hacer visible el criterio que normalmente queda oculto detrás de una buena oportunidad.', cards: [{ label: 'Fuente', title: 'Oportunidad real', desc: 'Un producto útil aparece a un precio favorable.' }, { label: 'Señal', title: 'Valor legible', desc: 'La referencia y la fecha de verificación explican el precio.' }, { label: 'Salida', title: 'Orden clara', desc: 'La conversación comienza con una orden concreta y trazable.' }] }
    : { title: 'A find becomes a better buy', body: 'APERFY technology is not here to perform by itself. It makes the judgment behind a good opportunity visible, so the product can speak clearly before a conversation begins.', cards: [{ label: 'Source', title: 'Real opportunity', desc: 'A useful product appears at a favorable price.' }, { label: 'Signal', title: 'Legible value', desc: 'The reference and verification date explain the price.' }, { label: 'Outcome', title: 'Clear order', desc: 'The conversation starts with a concrete, traceable order.' }] };
  const icons = [ScanLine, CircleCheck, ArrowUpRight];
  return <section className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="max-w-lg text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-4xl">{copy.title}</p><p className="mt-5 max-w-xl text-base leading-relaxed text-muted-foreground">{copy.body}</p></div><div className="grid gap-3">{copy.cards.map((card, index) => { const Icon = icons[index]; return <div key={card.label} className="group flex gap-4 rounded-2xl border border-border bg-card p-5 transition-colors hover:border-primary/40"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="h-4 w-4" aria-hidden="true" /></div><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">{card.label}</p><h3 className="mt-1 font-semibold">{card.title}</h3><p className="mt-1 text-sm text-muted-foreground">{card.desc}</p></div></div>; })}</div></section>;
}
