import { ArrowUpRight, CircleCheck, Package, ShoppingBag } from 'lucide-react';

export default function FindNarrative({ locale }: { locale: 'en' | 'es' }) {
  const copy = locale === 'es'
    ? { title: 'Una buena compra empieza con un buen deal', body: 'APERFY busca oportunidades de compra al mayor y las convierte en productos disponibles para tu día a día. Sin catálogo infinito: solo lo que tenemos ahora.', cards: [{ label: 'Origen', title: 'Compra al mayor', desc: 'Aprovechamos oportunidades de volumen cuando aparecen.' }, { label: 'Disponibilidad', title: 'Stock real', desc: 'Lo publicado es lo que puedes comprar hoy.' }, { label: 'Salida', title: 'Compra clara', desc: 'Revisas detalles, añades al carrito y coordinas tu orden.' }] }
    : { title: 'A good buy starts with a good deal', body: 'APERFY looks for bulk-buy opportunities and turns them into products available for everyday life. No endless catalog: only what we have now.', cards: [{ label: 'Source', title: 'Bulk buying', desc: 'We use volume opportunities when they appear.' }, { label: 'Availability', title: 'Real stock', desc: 'What is published is what you can buy today.' }, { label: 'Outcome', title: 'Clear checkout', desc: 'Review details, add to cart and coordinate your order.' }] };
  const icons = [ShoppingBag, CircleCheck, ArrowUpRight];
  return <section className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="max-w-lg text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-4xl">{copy.title}</p><p className="mt-5 max-w-xl text-base leading-relaxed text-muted-foreground">{copy.body}</p></div><div className="grid gap-3">{copy.cards.map((card, index) => { const Icon = icons[index]; return <div key={card.label} className="group flex gap-4 rounded-2xl border border-border bg-card p-5 transition-colors hover:border-primary/40"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="h-4 w-4" aria-hidden="true" /></div><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">{card.label}</p><h3 className="mt-1 font-semibold">{card.title}</h3><p className="mt-1 text-sm text-muted-foreground">{card.desc}</p></div></div>; })}</div></section>;
}
