import { Mail, MessageCircle, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useLanguage } from '@/i18n/LanguageContext';

export default function Contact() {
  const { language } = useLanguage();
  const es = language === 'es';
  return <main className="mx-auto max-w-4xl px-5 py-12 sm:px-8 sm:py-16 lg:px-12"><section className="rounded-3xl border border-primary/20 bg-card/55 p-7 shadow-[0_24px_80px_hsl(220_35%_2%/.25)] backdrop-blur-xl sm:p-12"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">APERFY · {es ? 'contacto' : 'contact'}</p><h1 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">{es ? 'Contacto APERFY' : 'Contact APERFY'}</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground">{es ? '¿Tienes una pregunta sobre un producto, una orden o una oferta? Escríbenos y te ayudaremos a encontrar la mejor opción disponible.' : 'Have a question about a product, an order, or a deal? Reach out and we will help you find the best available option.'}</p><div className="mt-9 grid gap-3 sm:grid-cols-2"><a href="mailto:hola@aperfy.kpwr.dev" className="group rounded-2xl border border-border bg-background/30 p-5 transition-colors hover:border-primary/45"><Mail className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">{es ? 'Escríbenos por email' : 'Email us'}</p><p className="mt-1 text-sm text-muted-foreground">hola@aperfy.kpwr.dev</p></a><Link to="/ask" className="group rounded-2xl border border-border bg-background/30 p-5 transition-colors hover:border-primary/45"><MessageCircle className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">{es ? 'Solicitar un producto' : 'Request a product'}</p><p className="mt-1 text-sm text-muted-foreground">{es ? 'Cuéntanos qué estás buscando.' : 'Tell us what you are looking for.'}</p><ArrowRight className="mt-4 h-4 w-4 text-primary transition-transform group-hover:translate-x-1" /></Link></div></section></main>;
}
